Repository parallaxsecond/parsec-interface-rs, pull requests merged in 2020-04, with the labels that each got.

#37 Add permits method to check for policy
  src/lib.rs
  src/operations/mod.rs
  src/operations/psa_algorithm.rs
  src/operations/psa_key_attributes.rs
Labels: enhancement

#38 Add a new method for permisison and compatibility
  src/operations/psa_key_attributes.rs
Labels: enhancement

#39 Add faillible methods
  src/operations/psa_algorithm.rs
  src/operations/psa_key_attributes.rs
Labels: enhancement

#42 Add body_type fn to Convert
  src/operations/mod.rs
  src/operations_protobuf/mod.rs
Labels: enhancement

#43 Remove wire protocol version from RequestHeader
  src/lib.rs
  src/requests/mod.rs
  src/requests/request/mod.rs
  src/requests/request/request_header.rs
  src/requests/response/mod.rs
  src/requests/response/response_header.rs
Labels: invalid

#47 Rename key id to key info
  src/requests/response_status.rs
Labels: invalid

#48 Breaking change to wire protocol 1.0 to support additional fields and transports
  Cargo.toml
  src/lib.rs
  src/requests/common/mod.rs
  src/requests/common/wire_header_1_0.rs
  src/requests/mod.rs
  src/requests/request/mod.rs
  src/requests/request/request_header.rs
  src/requests/response/mod.rs
  src/requests/response/response_header.rs
Labels: enhancement

#50 Modify Opcode size
  src/requests/mod.rs
Labels: bug
