Repository parallaxsecond/parsec-interface-rs, pull requests merged in 2020-09, with the labels that each got.

#77 Upgrade dependencies
  .github/workflows/nightly.yml
  Cargo.toml
  README.md
  src/operations/list_providers.rs
Labels: enhancement

#78 Fix nightly CI
  .github/workflows/nightly.yml
Labels: bug

#80 Prefix peer credentials with Unix
  src/requests/mod.rs
Labels: invalid

#81 Update wire protocol link in README
  README.md
Labels: documentation, invalid
